# yamllint disable rule:line-length
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# yamllint enable rule:line-length

---

name: .NET Tests

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main", "develop", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: [
          "windows-latest",
          "ubuntu-latest",
          "macOS-latest"
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Lint (codestyle)
        run: dotnet format --verify-no-changes --verbosity normal
      - name: Test
        run: dotnet test --no-build --verbosity normal
