# yamllint disable rule:line-length
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# yamllint enable rule:line-length

---

name: .NET Coverage

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore --verbosity normal
      - name: Build
        run: dotnet build --no-restore --verbosity normal
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.0.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
