---
name: gitleaks

on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@b63d6855b47b4f60b3d2d55b2ff6f72cb5e8feff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Only required for Organizations, not personal accounts.
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
